// ==UserScript==
// @name	Tieba Float Movable
// @namespace	http://gera2ld.blog.163.com/
// @author	Gerald <gera2ld@163.com>
// @icon	http://s.gravatar.com/avatar/a0ad718d86d21262ccd6ff271ece08a3?s=80
// @version	1.0.3
// @description	贴吧可移动悬浮窗
// @homepage	https://userscripts.org/scripts/show/156576
// @downloadURL	https://userscripts.org/scripts/source/156576.user.js
// @updateURL	https://userscripts.org/scripts/source/156576.meta.js
// @include	http://tieba.baidu.com/*
// @exclude	http://tieba.baidu.com/tb/*
// @require	https://userscripts.org/scripts/source/156795.user.js
// ==/UserScript==
function movable(t,e){function i(e){var i={};t.args.forEach(function(t){i[t]=/^-?\d+px/.test(e[t])?e[t]:"20px"}),$(t).css(i)}$(t).mousedown&&(t.moving=!1,t.args=["auto"==$(t).css("left")?"right":"left","auto"==$(t).css("top")?"bottom":"top"],$(t).mousedown(function(o){0>["DIV","TD"].indexOf(o.target.tagName)||"true"==o.target.contentEditable||(o.preventDefault(),o.stopPropagation(),this.x=o.pageX,this.args.indexOf("left")>=0?this.x-=parseInt($(this).css("left")):this.x+=parseInt($(this).css("right")),this.y=o.pageY,this.args.indexOf("top")>=0?this.y-=parseInt($(this).css("top")):this.y+=parseInt($(this).css("bottom")),this.moving||$(document).mousemove(function(e){if(t.moving){var o={};for(var a in t.args){var n=t.args[a];if("left"==n)o[n]=e.pageX-t.x;else if("right"==n)o[n]=t.x-e.pageX;else if("top"==n)o[n]=e.pageY-t.y;else{if("bottom"!=n)continue;o[n]=t.y-e.pageY}o[n]+="px"}i(o)}e.preventDefault()}).mouseup(function(){if(t.moving){t.moving=!1;var i={};for(var o in t.args){var a=t.args[o];i[a]=$(t).css(a)}utils.setObj("mcss_"+e,i),$(document).unbind("mousemove").unbind("mouseup")}}),this.moving=!0)}),i(utils.getObj("mcss_"+e,{})))}function unmovable(t){$(t).unbind("mousedown").css({left:"",right:"",top:"",bottom:""})}PageData&&PageData.user&&unsafeWindow.rich_postor&&function(){function t(d){if(d){if("dblclick"==d.type){if(""+unsafeWindow.rich_postor._editor.savedRange)return;a="open"==a?"close":"open"}else a="normal"==a?"open":"normal";utils.setObj("float",a)}r.hide(),d&&"click"!=d.type||("normal"==a?(o.html(""),i.html(""),p.val("悬浮"),n.unbind("dblclick"),unmovable(r[0]),n.removeProp("title"),n.attr("style",s)):(o.html(e),p.val("停靠"),n.dblclick(t),movable(r[0],"float"),n.removeProp("style"))),"open"==a?(i.html("#edit_parent{width:635px;}#edit_parent *{max-width:635px;}.tb-editor-editarea{min-height:50px !important;}.editor_tip_show{top:50px !important}"),n.attr("title","双击缩小，Ctrl+Enter快捷发表")):"close"==a&&(i.html("#edit_parent{width:360px;}#edit_parent *{max-width:360px;}.tb-editor-toolbar,#signNameWrapper,.pt_submit,.editor_users{display:none;}.tb-editor-wrapper{margin:0 !important}.tb-editor-editarea{min-height:24px !important;}.editor_tip_show{top:0 !important;left:60px !important;}.edit_title_field{padding:0 !important;}"),n.attr("title","双击展开，Ctrl+Enter快捷发表")),r.show()}var e="#signNameWrapper{margin:0 !important;}#edit_parent{border:3px double grey;position:fixed;z-index:998;background-color:#E7EAEB;}#edit_parent>table td:first-child,.new_tiezi_tip{display:none;}.editor_users{padding:0 !important;}.subTip{display:none;}.edit_title_field{margin:0 0 -5px !important;}.tb-editor-editarea{max-height:266px !important;}",i=utils.addStyle(),o=utils.addStyle(),a=utils.getObj("float","normal"),n=$(unsafeWindow.rich_postor._editor.editArea),r=$("#edit_parent"),s=n.attr("style"),p=utils.addSButton().click(t);t()}();