// ==UserScript==
// @name	Tieba Float Movable
// @namespace	http://gera2ld.blog.163.com/
// @author	Gerald <gera2ld@163.com>
// @icon	http://s.gravatar.com/avatar/a0ad718d86d21262ccd6ff271ece08a3?s=80
// @version	1.0.5
// @description	贴吧可移动悬浮窗
// @homepage	https://userscripts.org/scripts/show/156576
// @downloadURL	https://userscripts.org/scripts/source/156576.user.js
// @updateURL	https://userscripts.org/scripts/source/156576.meta.js
// @include	http://tieba.baidu.com/*
// @exclude	http://tieba.baidu.com/tb/*
// @require	https://raw.github.com/gera2ld/UserJS/master/lib/TiebaCommon.min.user.js
// ==/UserScript==
function t(t,i){function e(i){var e={};t.args.forEach(function(t){e[t]=/^-?\d+px/.test(i[t])?i[t]:"20px"}),$(t).css(e)}$(t).mousedown&&(t.moving=!1,t.args=[$(t).css("left")=="auto"?"right":"left",$(t).css("top")=="auto"?"bottom":"top"],$(t).mousedown(function(o){["DIV","TD"].indexOf(o.target.tagName)<0||o.target.contentEditable=="true"||(o.preventDefault(),o.stopPropagation(),this.x=o.pageX,this.args.indexOf("left")>=0?this.x-=parseInt($(this).css("left")):this.x+=parseInt($(this).css("right")),this.y=o.pageY,this.args.indexOf("top")>=0?this.y-=parseInt($(this).css("top")):this.y+=parseInt($(this).css("bottom")),this.moving||$(document).mousemove(function(i){if(t.moving){var o={};for(var a in t.args){var n=t.args[a];if("left"==n)o[n]=i.pageX-t.x;else if("right"==n)o[n]=t.x-i.pageX;else if("top"==n)o[n]=i.pageY-t.y;else{if("bottom"!=n)continue;o[n]=t.y-i.pageY}o[n]+="px"}e(o)}i.preventDefault()}).mouseup(function(){if(t.moving){t.moving=!1;var e={};for(var o in t.args){var a=t.args[o];e[a]=$(t).css(a)}utils.setObj("mcss_"+i,e),$(document).unbind("mousemove").unbind("mouseup")}}),this.moving=!0)}),e(utils.getObj("mcss_"+i,{})))}function i(t){$(t).unbind("mousedown").css({left:"",right:"",top:"",bottom:""})}PageData&&PageData.user&&unsafeWindow.rich_postor&&function(){function e(m){m&&(r=m.type=="dblclick"?"open"==r?"close":"open":"normal"==r?"open":"normal",utils.setObj("float",r)),p.hide(),m&&m.type!="click"||("normal"==r?(n.html(""),a.html(""),l.val("悬浮"),p.unbind("dblclick"),i(p[0]),p.removeProp("title"),s.attr("style",d)):(n.html(o),l.val("停靠"),p.dblclick(e),t(p[0],"float"),s.removeProp("style"))),"open"==r?(a.html("#edit_parent{width:635px;}#edit_parent *{max-width:635px;}.tb-editor-editarea{min-height:50px !important;}.editor_tip_show{top:50px !important}"),p.attr("title","双击收缩")):"close"==r&&(a.html("#edit_parent{width:360px;}#edit_parent *{max-width:360px;}.tb-editor-toolbar,#signNameWrapper,.pt_submit,.editor_users{display:none;}.tb-editor-wrapper{margin:0 !important}.tb-editor-editarea{min-height:24px !important;}.editor_tip_show{top:0 !important;left:60px !important;}.edit_title_field{padding:0 !important;}"),p.attr("title","双击展开")),p.show()}var o="#signNameWrapper{margin:0 !important;}#edit_parent{border:3px double grey;position:fixed;z-index:998;background-color:#E7EAEB;}#edit_parent>table td:first-child,.new_tiezi_tip{display:none;}.editor_users{padding:0 !important;}.subTip{display:none;}.edit_title_field{margin:0 0 -5px !important;}.tb-editor-editarea{max-height:266px !important;}",a=utils.addStyle(),n=utils.addStyle(),r=utils.getObj("float","normal"),s=$(unsafeWindow.rich_postor._editor.editArea),p=$("#edit_parent"),d=s.attr("style"),l=utils.addSButton().click(e);e()}();