// ==UserScript==
// @name	Tieba Multiuser
// @namespace	http://gera2ld.blog.163.com/
// @author	Gerald <gera2ld@163.com>
// @icon	http://s.gravatar.com/avatar/a0ad718d86d21262ccd6ff271ece08a3?s=80
// @version	1.1.2
// @description	百度贴吧马甲切换
// @homepage	https://userscripts.org/scripts/show/154072
// @downloadURL	https://userscripts.org/scripts/source/154072.user.js
// @updateURL	https://userscripts.org/scripts/source/154072.meta.js
// @include	http://tieba.baidu.com/*
// @grant	GM_getValue
// @grant	GM_setValue
// @grant	GM_addStyle
// ==/UserScript==
function switchUser(e,t){var n=new Date;e?n.setTime(16094e8):e="",document.cookie="BDUSS="+e+";domain=baidu.com;path=/;expires="+n.toGMTString(),"function"==typeof t?t():"string"==typeof t?location.replace(t):location.reload()}function save(){GM_setValue("ge_users",JSON.stringify(users))}function work(e){"com_userbar"==e.target.parentNode.id&&initTieba(e.target)}function init(){var e=GM_getValue("ge_users");e||(e=localStorage.getItem("ge_users"),e&&localStorage.removeItem("ge_users")),users=e?JSON.parse(e):{};var t=unsafeWindow.PageData;if(t.user&&t.user.is_login&&t.user.name){var n=document.cookie.match(/BDUSS=(.*?)(;|$)/);n&&(users[t.user.name]=n[1],save())}GM_addStyle("#ge_users>li{position:relative;cursor:pointer;}#ge_users span{background:#77f;color:white;border-radius:3px;border:1px solid;border:none;margin:2px;cursor:pointer;text-align:center;padding:0 2px;}"),document.body.addEventListener("DOMNodeInserted",work,!0)}function userClick(e){e.preventDefault(),e=e.target;var t;"A"==e.tagName?(t=null,/^\/i\//.test(location.pathname)&&(t="/"),e.nextSibling?switchUser(users[e.innerText||e.textContent],t):"未登录状态"==e.innerHTML?switchUser():"添加马甲"==e.innerHTML&&unsafeWindow.TbCom.process("User","buildLoginFrame")):"SPAN"==e.tagName&&(t=e.previousSibling,delete users[t.innerText||t.textContent],setTimeout(save,0),(t=t.parentNode).parentNode.removeChild(t))}function initTieba(e){document.body.removeEventListener("DOMNodeInserted",work,!0);var t=document.createElement("li");e.insertBefore(t,e.firstChild),t.className="split";var n=document.createElement("li");e.insertBefore(n,t),n.innerHTML="<a href=# class=u_arrow>马甲</a>",n.onmouseover=function(){t.style.display="block"},n.onmouseout=function(){t.style.display="none"},t=document.createElement("div"),n.appendChild(t),t.className="u_ddl",t.setAttribute("style","display:none;width:40px;top:-2px;"),e=document.createElement("div"),t.appendChild(e),e.className="u_ddl_con u_ddl_con_top";var r=document.createElement("ul");e.appendChild(r),r.id="ge_users",r.onclick=userClick,e=document.createElement("li"),e.innerHTML="<a href=#>未登录状态</a>",r.appendChild(e);for(var i in users)i?(e=document.createElement("li"),e.innerHTML="<a href=#>"+i.replace(/&/g,"&amp;").replace(/</g,"&lt;")+'</a><span style="position:absolute;right:0;top:0;">删除</span>',r.appendChild(e)):delete users[i];e=document.createElement("li"),e.innerHTML="<a href=#>添加马甲</a>",r.appendChild(e)}var users;document.querySelector(".s_nav")&&init();